"use client";

import { useState } from "react";
import ChartCard from "@/components/ChartCard";
import DataTable from "@/components/DataTable";

export default function ReportsPage() {
    const [reportType, setReportType] = useState("Weekly Wellness Summary");
    const [timeRange, setTimeRange] = useState("This Week");
    const [format, setFormat] = useState("PDF");
    const [generating, setGenerating] = useState(false);
    const [successMsg, setSuccessMsg] = useState(false);

    const [scope, setScope] = useState({
        "Hostel Data": true,
        "Zone Environmental Data": true,
        "Academic Calendar Overlay": true,
        "Semester Trends": true,
        "Burnout Alert Summary": true,
        "Nutrition Data": false
    });

    const handleScopeChange = (key: string) => {
        setScope(prev => ({ ...prev, [key]: !prev[key as keyof typeof prev] }));
    };

    const handleGenerate = () => {
        setGenerating(true);
        setTimeout(() => {
            setGenerating(false);
            setSuccessMsg(true);
            setTimeout(() => setSuccessMsg(false), 3000);
        }, 2000);
    };

    const reportTypes = [
        "Weekly Wellness Summary",
        "Hostel Comparison Report",
        "Burnout Risk Overview",
        "Academic Calendar Stress Correlation",
        "Semester Longitudinal Report"
    ];

    const timeRanges = ["This Week", "This Month", "This Semester", "Full Year"];

    const recentExports = [
        { name: "Weekly Wellness Summary", by: "Gauri Admin", date: "Feb 20 2026", format: "PDF", status: "Ready" },
        { name: "Hostel Comparison Report", by: "Gauri Admin", date: "Feb 18 2026", format: "CSV", status: "Ready" },
        { name: "Burnout Risk Overview", by: "Gauri Admin", date: "Feb 15 2026", format: "PDF", status: "Ready" },
    ];

    const columns = [
        {
            key: "name",
            label: "REPORT NAME",
            render: (row: typeof recentExports[0]) => <span style={{ fontWeight: 600, color: "var(--text-primary)" }}>{row.name}</span>
        },
        { key: "by", label: "GENERATED BY" },
        { key: "date", label: "DATE" },
        {
            key: "format",
            label: "FORMAT",
            render: (row: typeof recentExports[0]) => (
                <span className="badge" style={{ background: "var(--bg-elevated)", color: "var(--text-secondary)", border: "1px solid var(--border)" }}>
                    {row.format}
                </span>
            )
        },
        {
            key: "status",
            label: "STATUS",
            render: () => (
                <span className="badge badge-cyan" style={{ background: "var(--accent-glow)", color: "var(--accent)" }}>
                    ✓ Ready
                </span>
            )
        },
        {
            key: "download",
            label: "DOWNLOAD",
            render: () => (
                <button className="filter-btn" style={{ fontSize: "11px", padding: "4px 10px", color: "var(--text-primary)", background: "var(--bg-card)" }}>
                    ↓ Download
                </button>
            )
        }
    ];

    return (
        <>
            {/* Section 1: Privacy Banner */}
            <div className="animate-fade-in-up stagger-1" style={{
                background: "rgba(255,68,68,0.06)",
                border: "1px solid rgba(255,68,68,0.2)",
                borderRadius: "8px",
                padding: "12px 16px",
                marginBottom: "24px",
                color: "var(--text-primary)",
                fontSize: "14px",
                display: "flex",
                alignItems: "center",
                gap: "8px"
            }}>
                🔒 All exports enforce minimum group size of 10. Segments with fewer than 10 respondents are automatically suppressed. All exports are audit-logged.
            </div>

            <div className="page-header animate-fade-in-up stagger-2">
                <h1 className="page-title">Reports & Exports</h1>
                <p className="page-subtitle">
                    Generate compliant aggregate wellness reports and data exports
                </p>
            </div>

            {/* Section 2: Two Column Layout */}
            <div style={{ display: "flex", gap: "24px", marginBottom: "32px", flexWrap: "wrap" }} className="animate-fade-in-up stagger-3">
                {/* Left Column: Report Builder (40%) */}
                <div style={{ flex: "0 0 40%", minWidth: "320px", display: "flex", flexDirection: "column", gap: "16px" }}>
                    <ChartCard title="Report Builder">
                        {/* Step 1 */}
                        <div style={{ marginBottom: "20px" }}>
                            <div style={{ fontSize: "12px", color: "var(--text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "12px" }}>Step 1: Report Type</div>
                            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                {reportTypes.map(rt => (
                                    <div
                                        key={rt}
                                        onClick={() => setReportType(rt)}
                                        style={{
                                            padding: "12px 16px",
                                            borderRadius: "8px",
                                            cursor: "pointer",
                                            border: reportType === rt ? "1px solid var(--accent)" : "1px solid var(--border)",
                                            color: reportType === rt ? "var(--accent)" : "var(--text-secondary)",
                                            background: reportType === rt ? "var(--accent-glow)" : "var(--bg-elevated)",
                                            fontSize: "14px",
                                            fontWeight: reportType === rt ? 600 : 500,
                                            transition: "all 0.2s ease"
                                        }}
                                    >
                                        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                                            <div style={{
                                                width: "16px", height: "16px", borderRadius: "50%",
                                                border: reportType === rt ? "4px solid var(--accent)" : "1px solid var(--text-muted)",
                                                background: "transparent"
                                            }} />
                                            {rt}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Step 2 */}
                        <div style={{ marginBottom: "20px" }}>
                            <div style={{ fontSize: "12px", color: "var(--text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "12px" }}>Step 2: Time Range</div>
                            <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
                                {timeRanges.map(tr => (
                                    <button
                                        key={tr}
                                        onClick={() => setTimeRange(tr)}
                                        style={{
                                            padding: "8px 16px",
                                            borderRadius: "20px",
                                            border: "none",
                                            cursor: "pointer",
                                            background: timeRange === tr ? "var(--accent)" : "var(--bg-elevated)",
                                            color: timeRange === tr ? "#000" : "var(--text-secondary)",
                                            fontWeight: timeRange === tr ? 600 : 500,
                                            fontSize: "13px",
                                            transition: "all 0.2s ease"
                                        }}
                                    >
                                        {tr}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Step 3 */}
                        <div style={{ marginBottom: "20px" }}>
                            <div style={{ fontSize: "12px", color: "var(--text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "12px" }}>Step 3: Scope</div>
                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                                {Object.entries(scope).map(([key, isChecked]) => (
                                    <label key={key} style={{ display: "flex", alignItems: "center", gap: "8px", cursor: "pointer", fontSize: "13px", color: "var(--text-secondary)" }}>
                                        <input
                                            type="checkbox"
                                            checked={isChecked}
                                            onChange={() => handleScopeChange(key)}
                                            style={{ cursor: "pointer", accentColor: "var(--accent)", width: "16px", height: "16px" }}
                                        />
                                        {key}
                                    </label>
                                ))}
                            </div>
                        </div>

                        {/* Step 4 */}
                        <div style={{ marginBottom: "24px" }}>
                            <div style={{ fontSize: "12px", color: "var(--text-muted)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "12px" }}>Step 4: Format</div>
                            <div style={{ display: "flex", gap: "8px" }}>
                                {["PDF", "CSV"].map(f => (
                                    <button
                                        key={f}
                                        onClick={() => setFormat(f)}
                                        style={{
                                            flex: 1,
                                            padding: "10px",
                                            borderRadius: "8px",
                                            border: "1px solid var(--border)",
                                            cursor: "pointer",
                                            background: format === f ? "var(--accent)" : "var(--bg-elevated)",
                                            color: format === f ? "#000" : "var(--text-secondary)",
                                            fontWeight: format === f ? 600 : 500,
                                            fontSize: "14px",
                                            transition: "all 0.2s ease"
                                        }}
                                    >
                                        {f} Format
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Generate Button */}
                        <button
                            onClick={handleGenerate}
                            disabled={generating}
                            style={{
                                width: "100%",
                                padding: "14px",
                                borderRadius: "8px",
                                border: "none",
                                background: "var(--accent)",
                                color: "#000",
                                fontWeight: 800,
                                fontSize: "15px",
                                cursor: generating ? "not-allowed" : "pointer",
                                opacity: generating ? 0.7 : 1,
                                transition: "all 0.2s ease"
                            }}
                        >
                            {generating ? "⏳ Generating..." : `Generate ${format} Report`}
                        </button>

                        {successMsg && (
                            <div style={{
                                marginTop: "12px",
                                padding: "12px",
                                background: "var(--accent-glow)",
                                border: "1px solid var(--accent)",
                                borderRadius: "8px",
                                color: "var(--accent)",
                                fontSize: "13px",
                                fontWeight: 500,
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "center",
                                gap: "6px"
                            }}>
                                ✓ Report queued — download will begin shortly
                            </div>
                        )}
                    </ChartCard>
                </div>

                {/* Right Column: Report Preview (60%) */}
                <div style={{ flex: "1", minWidth: "320px", display: "flex", flexDirection: "column" }}>
                    <ChartCard title="Report Preview" badge="Live Simulator" className="preview-card-h-full">
                        <div style={{
                            background: "#0a0a0a",
                            border: "1px solid var(--border)",
                            borderRadius: "12px",
                            padding: "32px",
                            height: "100%",
                            display: "flex",
                            flexDirection: "column",
                            color: "var(--text-primary)"
                        }}>
                            <div style={{ fontSize: "24px", fontWeight: 700, marginBottom: "8px" }}>
                                {reportType}
                            </div>
                            <div style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "32px", display: "flex", gap: "12px", alignItems: "center" }}>
                                <span style={{ background: "var(--bg-elevated)", padding: "4px 10px", borderRadius: "4px" }}>{timeRange}</span>
                                <span style={{ background: "var(--bg-elevated)", padding: "4px 10px", borderRadius: "4px" }}>{format}</span>
                            </div>

                            <div style={{ display: "flex", flexDirection: "column", gap: "16px", marginBottom: "32px", flexGrow: 1 }}>
                                <div style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                                    <div style={{ color: "var(--green)", fontSize: "18px" }}>✓</div>
                                    <div style={{ fontSize: "15px", lineHeight: "1.5" }}>Campus Avg PWS <span style={{ fontWeight: 600 }}>78/100</span> up <span style={{ color: "var(--green)" }}>5.4%</span> vs last period</div>
                                </div>
                                <div style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                                    <div style={{ color: "var(--green)", fontSize: "18px" }}>✓</div>
                                    <div style={{ fontSize: "15px", lineHeight: "1.5" }}>Participation Rate <span style={{ fontWeight: 600 }}>68%</span> across 6 hostels</div>
                                </div>
                                <div style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                                    <div style={{ color: "var(--green)", fontSize: "18px" }}>✓</div>
                                    <div style={{ fontSize: "15px", lineHeight: "1.5" }}>Active Burnout Alerts <span style={{ fontWeight: 600 }}>24</span> with 3 cohorts flagged for review</div>
                                </div>
                                <div style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                                    <div style={{ color: "var(--green)", fontSize: "18px" }}>✓</div>
                                    <div style={{ fontSize: "15px", lineHeight: "1.5" }}>Highest wellness <span style={{ fontWeight: 600 }}>Govind Bhawan (85)</span> lowest <span style={{ fontWeight: 600 }}>Kasturba Bhawan (68)</span></div>
                                </div>
                            </div>

                            <div style={{
                                background: "rgba(255,159,67,0.1)",
                                border: "1px solid rgba(255,159,67,0.3)",
                                borderLeft: "4px solid var(--orange)",
                                borderRadius: "6px",
                                padding: "16px",
                                color: "var(--orange)",
                                fontSize: "14px",
                                display: "flex",
                                alignItems: "center",
                                gap: "10px",
                                marginTop: "auto"
                            }}>
                                <span style={{ fontSize: "16px" }}>⚠</span> 2 cohort segments suppressed in this report (group size below 10)
                            </div>
                        </div>
                    </ChartCard>
                </div>
            </div>

            {/* Section 3: Recent Exports Table */}
            <div className="animate-fade-in-up stagger-4">
                <DataTable title="Recent Exports" columns={columns} data={recentExports} />
            </div>
        </>
    );
}
