"use client";

import { useState, useEffect } from "react";
import ChartCard from "@/components/ChartCard";
import DataTable from "@/components/DataTable";
import api from "@/lib/api";

interface Report {
    id: number;
    name: string;
    by: string;
    date: string;
    format: string;
    status: string;
}

export default function ReportsPage() {
    const [reportType, setReportType] = useState("Weekly Wellness Summary");
    const [timeRange, setTimeRange] = useState("This Week");
    const [format, setFormat] = useState("CSV");
    const [generating, setGenerating] = useState(false);
    const [successMsg, setSuccessMsg] = useState(false);
    const [recentExports, setRecentExports] = useState<Report[]>([]);

    const [scope, setScope] = useState({
        "Hostel Data": true,
        "Zone Environmental Data": true,
        "Academic Calendar Overlay": true,
        "Semester Trends": true,
        "Burnout Alert Summary": true,
        "Nutrition Data": false
    });

    const fetchReports = async () => {
        try {
            const res = await api.get('/api/admin/reports');
            setRecentExports(res.data);
        } catch (error) {
            console.error("Failed to fetch reports:", error);
        }
    };

    useEffect(() => { fetchReports(); }, []);

    const handleScopeChange = (key: string) => {
        setScope(prev => ({ ...prev, [key]: !prev[key as keyof typeof prev] }));
    };

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            await new Promise(resolve => setTimeout(resolve, 1500));
            await api.post('/api/admin/reports', { name: reportType, format: format });

            // Generate a simple CSV for download based on selection
            const csvData = [
                ["Report Type", "Time Range", "Format"],
                [reportType, timeRange, format],
                [],
                ["Scope Options", "Enabled"],
                ...Object.entries(scope).map(([k, v]) => [k, v ? "Yes" : "No"])
            ];

            const csvContent = "data:text/csv;charset=utf-8," + csvData.map(e => e.join(",")).join("\n");
            const encodedUri = encodeURI(csvContent);
            const link = document.createElement("a");
            link.setAttribute("href", encodedUri);
            link.setAttribute("download", `${reportType.replace(/\\s+/g, '_')}_export.csv`);
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            setSuccessMsg(true);
            fetchReports();
            setTimeout(() => setSuccessMsg(false), 3000);
        } catch (error) {
            console.error("Failed to generate report:", error);
            alert("Error generating report.");
        } finally {
            setGenerating(false);
        }
    };

    const reportTypes = [
        "Weekly Wellness Summary",
        "Hostel Comparison Report",
        "Burnout Risk Overview",
        "Academic Calendar Stress Correlation",
        "Semester Longitudinal Report"
    ];

    const timeRanges = ["This Week", "This Month", "This Semester", "Full Year"];

    const columns = [
        {
            key: "name", label: "REPORT NAME",
            render: (row: Report) => <span style={{ fontWeight: 600, color: "var(--text-primary)" }}>{row.name}</span>
        },
        { key: "by", label: "GENERATED BY" },
        { key: "date", label: "DATE" },
        {
            key: "format", label: "FORMAT",
            render: (row: Report) => <span className="badge" style={{ background: "var(--bg-elevated)", color: "var(--text-secondary)", border: "1px solid var(--border)" }}>{row.format}</span>
        },
        {
            key: "status", label: "STATUS",
            render: () => <span className="badge badge-cyan">✓ Ready</span>
        },
        {
            key: "download", label: "DOWNLOAD",
            render: () => <button className="btn-ghost" style={{ fontSize: "11px", padding: "4px 10px" }}>↓ Download</button>
        }
    ];

    return (
        <>
            {/* Privacy Banner */}
            <div className="alert-banner alert-banner-warning animate-fade-in-up stagger-1">
                🔒 All exports enforce minimum group size of 10. Segments with fewer than 10 respondents are automatically suppressed. All exports are audit-logged.
            </div>

            <div className="page-header animate-fade-in-up stagger-2">
                <h1 className="page-title">Reports &amp; Exports</h1>
                <p className="page-subtitle">Generate compliant aggregate wellness reports and data exports</p>
            </div>

            {/* Two Column Layout */}
            <div className="report-builder-layout animate-fade-in-up stagger-3">
                {/* Left Column: Report Builder */}
                <div className="report-builder-left">
                    <ChartCard title="Report Builder">
                        {/* Step 1: Report Type */}
                        <div className="report-step">
                            <div className="report-step-label">Step 1: Report Type</div>
                            <div className="report-type-options">
                                {reportTypes.map(rt => (
                                    <div key={rt} onClick={() => setReportType(rt)} className={`report-type-option ${reportType === rt ? "active" : ""}`}>
                                        <div className="report-type-radio" />
                                        {rt}
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Step 2: Time Range */}
                        <div className="report-step">
                            <div className="report-step-label">Step 2: Time Range</div>
                            <div className="report-time-options">
                                {timeRanges.map(tr => (
                                    <button key={tr} onClick={() => setTimeRange(tr)} className={`report-time-btn ${timeRange === tr ? "active" : ""}`}>
                                        {tr}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Step 3: Scope */}
                        <div className="report-step">
                            <div className="report-step-label">Step 3: Scope</div>
                            <div className="report-scope-grid">
                                {Object.entries(scope).map(([key, isChecked]) => (
                                    <label key={key} className="report-scope-label">
                                        <input type="checkbox" checked={isChecked} onChange={() => handleScopeChange(key)} />
                                        {key}
                                    </label>
                                ))}
                            </div>
                        </div>

                        {/* Step 4: Format */}
                        <div className="report-step" style={{ marginBottom: "24px" }}>
                            <div className="report-step-label">Step 4: Format</div>
                            <div className="report-format-options">
                                {["CSV"].map(f => (
                                    <button key={f} onClick={() => setFormat(f)} className={`report-format-btn ${format === f ? "active" : ""}`}>
                                        {f} Format
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Generate Button */}
                        <button onClick={handleGenerate} disabled={generating} className="btn-primary" style={{ width: "100%", padding: "14px", fontSize: "15px" }}>
                            {generating ? "⏳ Generating..." : `Generate ${format} Report`}
                        </button>

                        {successMsg && (
                            <div className="report-success-msg">
                                ✓ Report queued — download will begin shortly
                            </div>
                        )}
                    </ChartCard>
                </div>

                {/* Right Column: Report Preview */}
                <div className="report-builder-right">
                    <ChartCard title="Report Preview" badge="Live Simulator" className="preview-card-h-full">
                        <div className="report-preview-container">
                            {/* Preview Header */}
                            <div className="rp-header">
                                <div className="rp-header-left">
                                    <div className="rp-report-icon">📊</div>
                                    <div>
                                        <div className="rp-title">{reportType}</div>
                                        <div className="rp-subtitle">Auto-generated preview based on current selections</div>
                                    </div>
                                </div>
                                <div className="rp-tags">
                                    <span className="rp-tag rp-tag-time">{timeRange}</span>
                                    <span className="rp-tag rp-tag-format">{format}</span>
                                </div>
                            </div>

                            {/* Metrics Grid */}
                            <div className="rp-metrics-grid">
                                {/* PWS Score Card */}
                                <div className="rp-metric-card">
                                    <div className="rp-metric-header">
                                        <span className="rp-metric-icon rp-icon-blue">💠</span>
                                        <span className="rp-metric-label">Campus Avg PWS</span>
                                    </div>
                                    <div className="rp-metric-body" style={{ alignItems: 'center' }}>
                                        <div className="rp-score-ring" style={{ width: 64, height: 64, minWidth: 64, position: 'relative' }}>
                                            <svg width="64" height="64" viewBox="0 0 80 80" className="rp-ring-svg" style={{ display: 'block' }}>
                                                <circle cx="40" cy="40" r="34" fill="none" stroke="var(--border)" strokeWidth="6" />
                                                <circle cx="40" cy="40" r="34" fill="none" stroke="var(--accent)" strokeWidth="6"
                                                    strokeDasharray={`${78 / 100 * 213.6} 213.6`}
                                                    strokeLinecap="round"
                                                    transform="rotate(-90 40 40)" />
                                            </svg>
                                            <div className="rp-ring-value">78</div>
                                        </div>
                                        <div className="rp-metric-detail">
                                            <span className="rp-trend rp-trend-up">↑ 5.4%</span>
                                            <span className="rp-trend-label">vs last period</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Participation Rate */}
                                <div className="rp-metric-card">
                                    <div className="rp-metric-header">
                                        <span className="rp-metric-icon rp-icon-green">👥</span>
                                        <span className="rp-metric-label">Participation Rate</span>
                                    </div>
                                    <div className="rp-metric-body rp-metric-body-col">
                                        <div className="rp-big-value">68<span className="rp-big-unit">%</span></div>
                                        <div className="rp-progress-track">
                                            <div className="rp-progress-fill" style={{ width: "68%" }} />
                                        </div>
                                        <span className="rp-metric-note">Across 6 hostels</span>
                                    </div>
                                </div>

                                {/* Burnout Alerts */}
                                <div className="rp-metric-card">
                                    <div className="rp-metric-header">
                                        <span className="rp-metric-icon rp-icon-red">🔥</span>
                                        <span className="rp-metric-label">Burnout Alerts</span>
                                    </div>
                                    <div className="rp-metric-body rp-metric-body-col">
                                        <div className="rp-big-value">24</div>
                                        <div className="rp-alert-badges">
                                            <span className="rp-alert-badge rp-badge-warn">3 cohorts flagged</span>
                                            <span className="rp-alert-badge rp-badge-info">Needs review</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Hostel Comparison */}
                                <div className="rp-metric-card">
                                    <div className="rp-metric-header">
                                        <span className="rp-metric-icon rp-icon-purple">🏠</span>
                                        <span className="rp-metric-label">Hostel Comparison</span>
                                    </div>
                                    <div className="rp-metric-body rp-metric-body-col">
                                        <div className="rp-hostel-row">
                                            <span className="rp-hostel-name">Govind Bhawan</span>
                                            <div className="rp-hostel-bar-track">
                                                <div className="rp-hostel-bar rp-bar-high" style={{ width: "85%" }} />
                                            </div>
                                            <span className="rp-hostel-score rp-score-high">85</span>
                                        </div>
                                        <div className="rp-hostel-row">
                                            <span className="rp-hostel-name">Kasturba Bhawan</span>
                                            <div className="rp-hostel-bar-track">
                                                <div className="rp-hostel-bar rp-bar-low" style={{ width: "68%" }} />
                                            </div>
                                            <span className="rp-hostel-score rp-score-low">68</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Privacy Suppression Notice */}
                            <div className="rp-privacy-notice">
                                <div className="rp-privacy-icon">🔒</div>
                                <div className="rp-privacy-text">
                                    <strong>2 cohort segments suppressed</strong> in this report — group size below minimum threshold of 10
                                </div>
                            </div>
                        </div>
                    </ChartCard>
                </div>
            </div>

            {/* Recent Exports Table */}
            <div className="animate-fade-in-up stagger-4">
                <DataTable title="Recent Exports" columns={columns} data={recentExports} />
            </div>
        </>
    );
}