"use client";

import { useState, useEffect } from "react";
import ChartCard from "@/components/ChartCard";
import DataTable from "@/components/DataTable";
import api from "@/lib/api";

interface Report {
    id: number;
    name: string;
    by: string;
    date: string;
    format: string;
    status: string;
}

export default function ReportsPage() {
    const [reportType, setReportType] = useState("Weekly Wellness Summary");
    const [timeRange, setTimeRange] = useState("This Week");
    const [format, setFormat] = useState("PDF");
    const [generating, setGenerating] = useState(false);
    const [successMsg, setSuccessMsg] = useState(false);
    const [recentExports, setRecentExports] = useState<Report[]>([]);

    const [scope, setScope] = useState({
        "Hostel Data": true,
        "Zone Environmental Data": true,
        "Academic Calendar Overlay": true,
        "Semester Trends": true,
        "Burnout Alert Summary": true,
        "Nutrition Data": false
    });

    const fetchReports = async () => {
        try {
            const res = await api.get('/api/admin/reports');
            setRecentExports(res.data);
        } catch (error) {
            console.error("Failed to fetch reports:", error);
        }
    };

    useEffect(() => { fetchReports(); }, []);

    const handleScopeChange = (key: string) => {
        setScope(prev => ({ ...prev, [key]: !prev[key as keyof typeof prev] }));
    };

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            await new Promise(resolve => setTimeout(resolve, 1500));
            await api.post('/api/admin/reports', { name: reportType, format: format });
            setSuccessMsg(true);
            fetchReports();
            setTimeout(() => setSuccessMsg(false), 3000);
        } catch (error) {
            console.error("Failed to generate report:", error);
            alert("Error generating report.");
        } finally {
            setGenerating(false);
        }
    };

    const reportTypes = [
        "Weekly Wellness Summary",
        "Hostel Comparison Report",
        "Burnout Risk Overview",
        "Academic Calendar Stress Correlation",
        "Semester Longitudinal Report"
    ];

    const timeRanges = ["This Week", "This Month", "This Semester", "Full Year"];

    const columns = [
        {
            key: "name", label: "REPORT NAME",
            render: (row: Report) => <span style={{ fontWeight: 600, color: "var(--text-primary)" }}>{row.name}</span>
        },
        { key: "by", label: "GENERATED BY" },
        { key: "date", label: "DATE" },
        {
            key: "format", label: "FORMAT",
            render: (row: Report) => <span className="badge" style={{ background: "var(--bg-elevated)", color: "var(--text-secondary)", border: "1px solid var(--border)" }}>{row.format}</span>
        },
        {
            key: "status", label: "STATUS",
            render: () => <span className="badge badge-cyan">✓ Ready</span>
        },
        {
            key: "download", label: "DOWNLOAD",
            render: () => <button className="btn-ghost" style={{ fontSize: "11px", padding: "4px 10px" }}>↓ Download</button>
        }
    ];

    return (
        <>
            {/* Privacy Banner */}
            <div className="alert-banner alert-banner-warning animate-fade-in-up stagger-1">
                🔒 All exports enforce minimum group size of 10. Segments with fewer than 10 respondents are automatically suppressed. All exports are audit-logged.
            </div>

            <div className="page-header animate-fade-in-up stagger-2">
                <h1 className="page-title">Reports &amp; Exports</h1>
                <p className="page-subtitle">Generate compliant aggregate wellness reports and data exports</p>
            </div>

            {/* Two Column Layout */}
            <div className="report-builder-layout animate-fade-in-up stagger-3">
                {/* Left Column: Report Builder */}
                <div className="report-builder-left">
                    <ChartCard title="Report Builder">
                        {/* Step 1: Report Type */}
                        <div className="report-step">
                            <div className="report-step-label">Step 1: Report Type</div>
                            <div className="report-type-options">
                                {reportTypes.map(rt => (
                                    <div key={rt} onClick={() => setReportType(rt)} className={`report-type-option ${reportType === rt ? "active" : ""}`}>
                                        <div className="report-type-radio" />
                                        {rt}
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Step 2: Time Range */}
                        <div className="report-step">
                            <div className="report-step-label">Step 2: Time Range</div>
                            <div className="report-time-options">
                                {timeRanges.map(tr => (
                                    <button key={tr} onClick={() => setTimeRange(tr)} className={`report-time-btn ${timeRange === tr ? "active" : ""}`}>
                                        {tr}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Step 3: Scope */}
                        <div className="report-step">
                            <div className="report-step-label">Step 3: Scope</div>
                            <div className="report-scope-grid">
                                {Object.entries(scope).map(([key, isChecked]) => (
                                    <label key={key} className="report-scope-label">
                                        <input type="checkbox" checked={isChecked} onChange={() => handleScopeChange(key)} />
                                        {key}
                                    </label>
                                ))}
                            </div>
                        </div>

                        {/* Step 4: Format */}
                        <div className="report-step" style={{ marginBottom: "24px" }}>
                            <div className="report-step-label">Step 4: Format</div>
                            <div className="report-format-options">
                                {["PDF", "CSV"].map(f => (
                                    <button key={f} onClick={() => setFormat(f)} className={`report-format-btn ${format === f ? "active" : ""}`}>
                                        {f} Format
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Generate Button */}
                        <button onClick={handleGenerate} disabled={generating} className="btn-primary" style={{ width: "100%", padding: "14px", fontSize: "15px" }}>
                            {generating ? "⏳ Generating..." : `Generate ${format} Report`}
                        </button>

                        {successMsg && (
                            <div className="report-success-msg">
                                ✓ Report queued — download will begin shortly
                            </div>
                        )}
                    </ChartCard>
                </div>

                {/* Right Column: Report Preview */}
                <div className="report-builder-right">
                    <ChartCard title="Report Preview" badge="Live Simulator" className="preview-card-h-full">
                        <div className="report-preview-container">
                            <div className="report-preview-title">{reportType}</div>
                            <div className="report-preview-tags">
                                <span className="report-preview-tag">{timeRange}</span>
                                <span className="report-preview-tag">{format}</span>
                            </div>
                            <div className="report-preview-items">
                                <div className="report-preview-item">
                                    <div className="report-preview-check">✓</div>
                                    <div className="report-preview-text">Campus Avg PWS <strong>78/100</strong> up <span style={{ color: "var(--green)" }}>5.4%</span> vs last period</div>
                                </div>
                                <div className="report-preview-item">
                                    <div className="report-preview-check">✓</div>
                                    <div className="report-preview-text">Participation Rate <strong>68%</strong> across 6 hostels</div>
                                </div>
                                <div className="report-preview-item">
                                    <div className="report-preview-check">✓</div>
                                    <div className="report-preview-text">Active Burnout Alerts <strong>24</strong> with 3 cohorts flagged for review</div>
                                </div>
                                <div className="report-preview-item">
                                    <div className="report-preview-check">✓</div>
                                    <div className="report-preview-text">Highest wellness <strong>Govind Bhawan (85)</strong> lowest <strong>Kasturba Bhawan (68)</strong></div>
                                </div>
                            </div>
                            <div className="report-preview-warning">
                                <span style={{ fontSize: "16px" }}>⚠</span> 2 cohort segments suppressed in this report (group size below 10)
                            </div>
                        </div>
                    </ChartCard>
                </div>
            </div>

            {/* Recent Exports Table */}
            <div className="animate-fade-in-up stagger-4">
                <DataTable title="Recent Exports" columns={columns} data={recentExports} />
            </div>
        </>
    );
}